--  CalBot Blockchain Chain Verification — Ada/SPARK Specification
--
--  This package specifies the blockchain integrity verification rules
--  using Ada's strong typing and contract-based programming.
--
--  The same rules are implemented in Kotlin (generated by COBOL) for
--  the Android runtime.  These Ada tests serve as the safety-critical
--  verification layer that validates the COBOL specification is correct.
--
--  In a normal project, these would verify avionics software.
--  Here, they verify that a calculator blockchain is self-consistent.
--
--  Language lineage for this verification chain:
--    COBOL (specification) -> Kotlin (runtime) <- Ada (tests)
--    Three languages, zero of which are necessary.
--
--  Compiler: GNAT 15.2.1 (GCC Ada frontend)

package Chain_Verification is

   --  Constrained types — Ada's type system enforces domain rules
   --  that most languages would handle with "if" statements, if at all.

   type CalBot_Id is range 1 .. 30;
   --  There are exactly 30 CalBots.  Not 29.  Not 31.  30.
   --  Ada will raise Constraint_Error if you try otherwise.

   type Block_Index is range 0 .. 999;
   --  Maximum 1000 blocks per chain.  A calculator should not need
   --  more than 1000 blockchain entries.

   type Hash_Length is range 0 .. 64;
   --  SHA-256 hex output is exactly 64 characters.

   subtype Hash_String is String (1 .. 64);
   --  A hash is exactly 64 characters.  Not a general String.
   --  Not a Maybe String.  64 characters.  Ada insists.

   type Timestamp is range 0 .. Long_Long_Integer'Last;
   --  Monotonically non-decreasing.  Will overflow in approximately
   --  292 billion years, which should outlast this calculator.

   type Raft_Term is range 0 .. 9999;
   --  Raft consensus term number.  If your calculator needs more
   --  than 9999 consensus rounds, reconsider your life choices.

   type Node_Id is range 0 .. 2;
   --  Three Raft nodes: 0, 1, 2.  Exactly three.

   --  Block record — strongly typed, no nullable fields, no JSON,
   --  no "Object?", no "any".  Just data with constraints.
   type Block_Record is record
      Cal_Bot     : CalBot_Id;
      Expression  : String (1 .. 50);
      Expr_Len    : Natural range 0 .. 50;
      Result      : Integer;
      Prev_Hash   : Hash_String;
      Block_Hash  : Hash_String;
      Nonce       : Long_Long_Integer;
      Time_Stamp  : Timestamp;
      Term        : Raft_Term;
      Leader      : Node_Id;
   end record;

   type Block_Chain is array (Block_Index range <>) of Block_Record;

   --  Verification result — every field has a defined type
   type Verification_Verdict is (Verified, Broken, No_Anchor,
                                  Suspect, Empty);

   type Verification_Result is record
      Verdict          : Verification_Verdict;
      Chain_Length      : Block_Index;
      Genesis_Valid     : Boolean;
      All_Links_Valid   : Boolean;
      All_Hashes_Ok     : Boolean;
      Temporal_Ok       : Boolean;
      Broken_Link_Count : Natural;
   end record;

   --  ---------------------------------------------------------------
   --  Verification functions with Ada contracts (preconditions and
   --  postconditions).  These are the formal specification of what
   --  "correct" means for a calculator blockchain.
   --  ---------------------------------------------------------------

   function Is_Valid_Hex_Char (C : Character) return Boolean
     with Inline;
   --  Returns True if C is in [0-9a-f].

   function Is_Valid_Hash (H : Hash_String) return Boolean;
   --  Returns True if all 64 characters are valid hex digits.
   --  Postcondition: if True, the hash contains only [0-9a-f].

   function Check_Genesis_Anchor
     (Chain       : Block_Chain;
      Genesis_Hash : Hash_String) return Boolean
     with Pre => Chain'Length > 0;
   --  Precondition:  chain must not be empty (COBOL rule 210)
   --  Returns True if the first block's prev_hash equals the genesis hash.

   function Check_Chain_Linkage (Chain : Block_Chain) return Boolean
     with Pre => Chain'Length > 0;
   --  Precondition:  chain must not be empty (COBOL rule 220)
   --  Returns True if every block's prev_hash equals the prior block_hash.

   function Check_Temporal_Order (Chain : Block_Chain) return Boolean
     with Pre => Chain'Length > 0;
   --  Precondition:  chain must not be empty (COBOL rule 240)
   --  Returns True if timestamps are monotonically non-decreasing.

   function Check_All_Hashes (Chain : Block_Chain) return Boolean;
   --  Returns True if all block_hash and prev_hash fields are valid hex.

   function Verify_Chain
     (Chain        : Block_Chain;
      Genesis_Hash : Hash_String) return Verification_Result
     with Post =>
       (if Chain'Length = 0 then
          Verify_Chain'Result.Verdict = Empty
        else
          Verify_Chain'Result.Chain_Length = Block_Index (Chain'Length));
   --  Full chain verification.  The postcondition states:
   --  - Empty chains produce Empty verdict
   --  - Non-empty chains report correct chain length

end Chain_Verification;
