package edu.singaporetech.inf2007quiz01
 
import edu.singaporetech.inf2007quiz01.data.local.BlockEntity
import java.security.MessageDigest
 
/**
 * Blockchain integrity verifier for CalBot.
 *
 * THIS FILE IS GENERATED BY COBOL.
 * Do not edit manually.
 *
 * Generated by: chain_verifier_generator.cob
 * Compiler: GCC gcobol 15.2.1
 * Language: COBOL-85
 *
 * The verification logic herein was specified in
 * COBOL PROCEDURE DIVISION paragraphs and emitted
 * as Kotlin source code.  The COBOL source is the
 * canonical enterprise specification; this Kotlin
 * is the portable runtime implementation.
 *
 * Verification rules (from COBOL specification):
 *   1. Genesis anchor: first block prevHash must
 *      match the COBOL-generated genesis hash
 *   2. Chain linkage: each block prevHash must
 *      equal the preceding block blockHash
 *   3. Hash format: all hashes must be 64 hex chars
 *   4. Temporal ordering: timestamps must be
 *      monotonically non-decreasing
 *   5. Proof-of-work: blockHash must have the
 *      required leading zero prefix
 *
 * Audit report format uses COBOL PICTURE clause
 * field widths for proper enterprise formatting:
 *   CALBOT-ID:  PIC 9(4)
 *   BLOCK-SEQ:  PIC 9(6)
 *   EXPRESSION: PIC X(50)
 *   RESULT:     PIC S9(10)
 *   HASH:       PIC X(8)
 *   TIMESTAMP:  PIC 9(18)
 *   VERDICT:    PIC X(10)
 */
object BlockchainVerifier {
 
    /**
     * Result of a full chain integrity verification.
     * Field widths specified in COBOL PICTURE clauses.
     */
    data class VerificationResult(
        val calBotId: Int,
        val chainLength: Int,
        val genesisValid: Boolean,
        val allLinksValid: Boolean,
        val allHashesWellFormed: Boolean,
        val temporalOrderValid: Boolean,
        val brokenLinkIndices: List<Int>,
        val auditReport: String,
        val integrityProofHash: String,
        val verdict: String
    ) {
        val isFullyValid: Boolean get() =
            genesisValid && allLinksValid && allHashesWellFormed && temporalOrderValid
    }
 
    /**
     * Verify the integrity of a CalBot's blockchain.
     *
     * Implements the COBOL-specified verification rules:
     *   PERFORM 210-CHECK-GENESIS-ANCHOR
     *   PERFORM 220-CHECK-CHAIN-LINKAGE
     *   PERFORM 230-CHECK-HASH-FORMAT
     *   PERFORM 240-CHECK-TEMPORAL-ORDER
     */
    fun verifyChain(
        calBotId: Int,
        blocks: List<BlockEntity>
    ): VerificationResult {
        if (blocks.isEmpty()) {
            return VerificationResult(
                calBotId = calBotId,
                chainLength = 0,
                genesisValid = true,
                allLinksValid = true,
                allHashesWellFormed = true,
                temporalOrderValid = true,
                brokenLinkIndices = emptyList(),
                auditReport = "CHAIN EMPTY -- NO BLOCKS TO VERIFY",
                integrityProofHash = ZERO_PROOF,
                verdict = "EMPTY"
            )
        }
 
        // Sort by timestamp ascending (oldest first)
        val sorted = blocks.sortedBy { it.timestamp }
 
        // 210-CHECK-GENESIS-ANCHOR
        val genesisHash = GenesisBlocks.hashes[calBotId]
            ?: GenesisBlocks.ZERO_HASH
        val genesisValid = sorted.first().prevHash == genesisHash
 
        // 220-CHECK-CHAIN-LINKAGE
        val brokenLinks = mutableListOf<Int>()
        for (i in 1 until sorted.size) {
            if (sorted[i].prevHash != sorted[i - 1].blockHash) {
                brokenLinks.add(i)
            }
        }
 
        // 230-CHECK-HASH-FORMAT
        val hexPattern = Regex("^[0-9a-f]{64}$")
        val allHashesOk = sorted.all {
            hexPattern.matches(it.blockHash) && hexPattern.matches(it.prevHash)
        }
 
        // 240-CHECK-TEMPORAL-ORDER
        val temporalOk = sorted.zipWithNext().all {
            (a, b) -> b.timestamp >= a.timestamp
        }
 
        // Generate audit report and integrity proof
        val report = formatAuditReport(calBotId, sorted, genesisValid,
            brokenLinks, allHashesOk, temporalOk)
        val proof = computeIntegrityProof(calBotId, sorted)
 
        val verdict = when {
            genesisValid && brokenLinks.isEmpty() && allHashesOk && temporalOk ->
                "VERIFIED"
            brokenLinks.isNotEmpty() ->
                "BROKEN"
            !genesisValid ->
                "NO ANCHOR"
            else ->
                "SUSPECT"
        }
 
        return VerificationResult(
            calBotId = calBotId,
            chainLength = sorted.size,
            genesisValid = genesisValid,
            allLinksValid = brokenLinks.isEmpty(),
            allHashesWellFormed = allHashesOk,
            temporalOrderValid = temporalOk,
            brokenLinkIndices = brokenLinks,
            auditReport = report,
            integrityProofHash = proof,
            verdict = verdict
        )
    }
 
    /**
     * Format a COBOL-style audit report.
     */
    private fun formatAuditReport(
        calBotId: Int,
        blocks: List<BlockEntity>,
        genesisValid: Boolean,
        brokenLinks: List<Int>,
        allHashesOk: Boolean,
        temporalOk: Boolean
    ): String {
        val sb = StringBuilder()
 
        sb.appendLine("=" .repeat(72))
        sb.appendLine("  CALBOT BLOCKCHAIN INTEGRITY AUDIT REPORT")
        sb.appendLine("  GENERATED BY: COBOL CHAIN VERIFIER (gcobol 15.2.1)")
        sb.appendLine(
            "  CALBOT-ID: ${calBotId.toString()}")
        sb.appendLine(
            "  CHAIN-LENGTH: ${blocks.size}")
        sb.appendLine(
            "  GENESIS-ANCHOR: ${if (genesisValid) "VALID" else "INVALID"}")
        sb.appendLine("=" .repeat(72))
 
        for ((idx, block) in blocks.withIndex()) {
            val seq = idx.toString().padStart(6, '0')
            val expr = block.expression.padEnd(20)
            val res = block.result.toString().padStart(10)
            val hash = block.blockHash.take(8)
            val prev = block.prevHash.take(8)
            val link = if (idx in brokenLinks) "BROKEN" else "OK"
            sb.appendLine(
                "  BLK-$seq | $expr | $res | H:$hash | P:$prev | $link")
        }
 
        sb.appendLine("=" .repeat(72))
        val overallVerdict = when {
            genesisValid && brokenLinks.isEmpty() && allHashesOk && temporalOk ->
                "CHAIN INTEGRITY: VERIFIED"
            else ->
                "CHAIN INTEGRITY: FAILED"
        }
        sb.appendLine("  $overallVerdict")
        sb.appendLine(
            "  BROKEN-LINKS: ${brokenLinks.size}")
        sb.appendLine(
            "  HASH-FORMAT: ${if (allHashesOk) "CONFORMANT" else "NON-CONFORMANT"}")
        sb.appendLine(
            "  TEMPORAL-ORDER: ${if (temporalOk) "MONOTONIC" else "DISORDERED"}")
        sb.appendLine("=" .repeat(72))
        sb.appendLine("  END OF AUDIT REPORT")
        sb.appendLine("  -- THIS REPORT WAS SPECIFIED IN COBOL --")
 
        return sb.toString()
    }
 
    /**
     * Compute a SHA-256 integrity proof over
     * the entire chain.
     */
    private fun computeIntegrityProof(
        calBotId: Int,
        blocks: List<BlockEntity>
    ): String {
        val digest = MessageDigest.getInstance("SHA-256")
        digest.update(calBotId.toString().toByteArray())
        for (block in blocks) {
            digest.update(block.blockHash.toByteArray())
            digest.update(block.prevHash.toByteArray())
            digest.update(block.expression.toByteArray())
            digest.update(block.result.toString().toByteArray())
            digest.update(block.nonce.toString().toByteArray())
        }
        return digest.digest().joinToString("") { "%02x".format(it) }
    }
 
    private const val ZERO_PROOF =
        "0000000000000000000000000000000000000000000000000000000000000000"
}
