package edu.singaporetech.inf2007quiz01
 
/**
 * Genesis block hashes for each CalBot.
 *
 * THIS FILE IS GENERATED BY COBOL.
 * Do not edit manually.
 *
 * Generated by: genesis_generator.cob
 * Compiler: GCC gcobol 15.2.1
 * Language: COBOL-85
 *
 * The hashes are deterministic per CalBot ID so
 * the blockchain is reproducible across rebuilds.
 */
object GenesisBlocks {
 
    val hashes: Map<Int, String> = mapOf(
        1 to "e9f697a8dc33d926435c4cd9a7ca1f824fc53d93b63c39e552c40a101604c5fe",
        2 to "832fa7c5d4dac799a321afb53e899e6112d158e9db7a9a4f1f6952fa850890fe",
        3 to "1c69b8e3cb81b50b03e71291d6481d3fd6dd743f01b7fabaed0f9ae5f40c5bfe",
        4 to "b6a2c801c228a37d63ad746c6e079c1e99ea8f9626f55a25bab4e2d0620f25fd",
        5 to "4fdcd91eb9cf91efc372d74805c61cfc5cf6aaec4b33bb8f87592abbd113f0fd",
        6 to "e915ea3cb176806123383a249d859bdb2002c54271701bfa55fe72a63f17bbfc",
        7 to "824ffa5aa81d6ed482fe9d0035441ab9e30fe19896ae7c6422a4ba90ae1b86fc",
        8 to "1c880b779fc45c46e2c3ffdbcc039998a61bfcefbbecdccfef49027b1c1e51fb",
        9 to "b5c21b95976b4ab8428962b764c219766a271745e0293d39bdee4a668b221cfb",
        10 to "4efb2cb38e12382aa24fc593fb8098552d33329b06679da48a939251f926e7fb",
        11 to "e8353cd185b9269c0214286f933f1733f0404df22ba4fe0f5739da3c6829b1fa",
        12 to "816e4dee7c60140e62da8a4b2bfe9612b44c694850e25e7925de2226d72d7cfa",
        13 to "1ba85d0c74070281c2a0ed26c2bd16f07758849e7620bfe4f2836a11453147f9",
        14 to "b4e16e2a6baef1f3226550025a7c95cf3a659ff59b5d1f4ebf28b2fcb43512f9",
        15 to "4e1b7f476255df65812bb3def23b14adfe71ba4bc09b80b98dcefae72238ddf8",
        16 to "e7548f6559fccdd7e1f015ba89fa938cc17dd6a1e6d8e0245a7342d2913ca8f8",
        17 to "818da08351a3bb4941b6789521b9126a8489f1f70b16418e28188abdff4072f8",
        18 to "1ac7b0a0484aa9bba17cdb71b978924948960c4e3054a1f9f5bdd2a76e433df7",
        19 to "b400c1be3ff1972e01413e4d503711270ba227a455910263c2631a92dc4708f7",
        20 to "4d3ad1dc369885a06107a029e8f69005cfae42fa7bcf62ce9008627d4b4bd3f6",
        21 to "e673e2f92e3f7312c1cd030580b50fe492ba5e51a00cc3385dadaa68b94f9ef6",
        22 to "80adf21725e66284219266e017748fc255c779a7c54a23a32a52f253285269f5",
        23 to "19e603351c8d50f68158c9bcaf330ea119d394fdeb88840ef8f83a3d975633f5",
        24 to "b320145313343e68e01e2b9847f18d7fdcdfaf5410c5e478c59d8228055afef5",
        25 to "4c5924700bdb2cdb40e38e74deb00c5e9feccbaa350345e39242ca13745dc9f4",
        26 to "e693358e02821a4da0a9f14f766f8c3c63f8e6005a40a54d60e712fee26194f4",
        27 to "7fcc45acf92908bf006f542b0e2e0b1b26040156807e06b82d8d5ae951655ff3",
        28 to "190656c9f0d0f6316034b607a5ed8af9e9101cada5bc6622fa32a2d4bf692af3",
        29 to "b23f66e7e877e4a3c0fa19e33dac09d8ad1d3703caf9c78dc8d7eabe2e6cf5f2",
        30 to "4c797705df1ed31620bf7cbfd46b89b670295359f03727f8957c32a99c70bff2"
    )
 
    /** The zero-hash used when a CalBot has no previous block. */
    val ZERO_HASH: String = "0000000000000000000000000000000000000000000000000000000000000000"
}
