1  REM ============================================
2  REM  CALBOT BLOCKCHAIN VERIFICATION SYSTEM
3  REM  LANGUAGE: BASIC (1964)
4  REM  PURPOSE: ABSOLUTELY NONE
5  REM ============================================
6  REM  THIS PROGRAM CONTRIBUTES NOTHING TO THE
7  REM  CALCULATOR APP.  IT EXISTS SOLELY TO ADD
8  REM  BASIC TO THE LANGUAGE COUNT.
9  REM ============================================
10 PRINT "CALBOT BASIC VERIFICATION MODULE V1.0"
11 PRINT "INITIALIZING BLOCKCHAIN AUDIT..."
12 LET A = 2
13 LET B = 2
14 LET C = A + B
15 PRINT "COMPUTING: "; A; " + "; B; " = "; C
16 IF C <> 4 THEN GOTO 45
17 PRINT "ARITHMETIC CHECK: PASS"
18 PRINT "BEGINNING INFINITE VERIFICATION LOOP..."
19 PRINT "  (THIS IS THE ENTIRE PROGRAM)"
20 GOTO 10
21 REM --- THE ABOVE LINE IS THE WHOLE POINT ---
22 REM --- 20 GOTO 10. THAT IS THE PROGRAM.  ---
23 REM --- EVERYTHING ELSE IS DECORATION.     ---
24 REM ============================================
25 REM  DEAD CODE BELOW THIS POINT.
26 REM  THE GOTO ON LINE 20 ENSURES NONE OF
27 REM  THIS WILL EVER EXECUTE.  BUT IT PADS
28 REM  THE LINE COUNT TO 50.
29 REM ============================================
30 PRINT "ERROR: YOU SHOULD NOT BE HERE"
31 LET X = 0
32 FOR I = 1 TO 10
33 LET X = X + I
34 NEXT I
35 PRINT "TRIANGULAR NUMBER: "; X
36 REM  THE ABOVE COMPUTES 55 AND NOBODY CARES
37 LET FIB1 = 0
38 LET FIB2 = 1
39 FOR J = 1 TO 10
40 LET FIB3 = FIB1 + FIB2
41 LET FIB1 = FIB2
42 LET FIB2 = FIB3
43 NEXT J
44 PRINT "FIB(10) = "; FIB2
45 REM  THIS ONLY RUNS IF 2+2 IS NOT 4
46 PRINT "FATAL: ARITHMETIC FAILURE DETECTED"
47 PRINT "THE UNIVERSE IS BROKEN"
48 PRINT "CONTACT YOUR NEAREST COBOL PROGRAMMER"
49 END
50 REM  50 LINES OF BASIC. YOU ARE WELCOME.
