>>SOURCE FORMAT IS FREE

*> CalBot Blockchain Integrity Verifier Generator
*>
*> A COBOL program that generates a Kotlin source file containing
*> the blockchain chain verification logic for CalBot.
*>
*> This is COBOL acting as a transpiler: a language from 1959
*> emitting code for a language from 2011, which verifies a
*> blockchain whose genesis block hashes were also generated by
*> COBOL (see genesis_generator.cob).
*>
*> The generated Kotlin runs on all architectures (arm64, x86_64)
*> because it compiles to JVM bytecode.  The COBOL source is the
*> "enterprise specification" — the canonical definition of what
*> constitutes a valid blockchain for a calculator app.
*>
*> Build pipeline:
*>   COBOL (specification) -> gcobol (compiler) -> ELF (generator)
*>   -> Kotlin (emitted source) -> kotlinc (compiler) -> DEX (app)
*>
*> Compile: gcobol chain_verifier_generator.cob
*>              -o chain_verifier_generator
*> Run:     ./chain_verifier_generator > BlockchainVerifier.kt
*>
*> Language count update: COBOL is now responsible for TWO generated
*> Kotlin files in this project (GenesisBlocks.kt and this one).
*> The enterprise is expanding.

identification division.
program-id. chain-verifier-generator.

data division.
working-storage section.

*> Indentation control — Kotlin needs 4-space indents.
*> COBOL programs formatting whitespace-sensitive languages
*> is a special kind of irony.
01 ws-i1          pic x(4) value "    ".
01 ws-i2          pic x(8) value "        ".
01 ws-i3          pic x(12) value "            ".
01 ws-i4          pic x(16) value "                ".

procedure division.
    perform 100-emit-header
    perform 200-emit-verification-logic
    perform 300-emit-audit-formatter
    perform 400-emit-integrity-proof
    perform 500-emit-footer
    stop run.

*> ============================================================
*> Section 100: File header and class declaration
*> ============================================================
100-emit-header.
    display "package edu.singaporetech.inf2007quiz01"
    display " "
    display "import edu.singaporetech.inf2007quiz01.data.local"
        ".BlockEntity"
    display "import java.security.MessageDigest"
    display " "
    display "/**"
    display " * Blockchain integrity verifier for CalBot."
    display " *"
    display " * THIS FILE IS GENERATED BY COBOL."
    display " * Do not edit manually."
    display " *"
    display " * Generated by: chain_verifier_generator.cob"
    display " * Compiler: GCC gcobol 15.2.1"
    display " * Language: COBOL-85"
    display " *"
    display " * The verification logic herein was specified in"
    display " * COBOL PROCEDURE DIVISION paragraphs and emitted"
    display " * as Kotlin source code.  The COBOL source is the"
    display " * canonical enterprise specification; this Kotlin"
    display " * is the portable runtime implementation."
    display " *"
    display " * Verification rules (from COBOL specification):"
    display " *   1. Genesis anchor: first block prevHash must"
    display " *      match the COBOL-generated genesis hash"
    display " *   2. Chain linkage: each block prevHash must"
    display " *      equal the preceding block blockHash"
    display " *   3. Hash format: all hashes must be 64 hex chars"
    display " *   4. Temporal ordering: timestamps must be"
    display " *      monotonically non-decreasing"
    display " *   5. Proof-of-work: blockHash must have the"
    display " *      required leading zero prefix"
    display " *"
    display " * Audit report format uses COBOL PICTURE clause"
    display " * field widths for proper enterprise formatting:"
    display " *   CALBOT-ID:  PIC 9(4)"
    display " *   BLOCK-SEQ:  PIC 9(6)"
    display " *   EXPRESSION: PIC X(50)"
    display " *   RESULT:     PIC S9(10)"
    display " *   HASH:       PIC X(8)"
    display " *   TIMESTAMP:  PIC 9(18)"
    display " *   VERDICT:    PIC X(10)"
    display " */"
    display "object BlockchainVerifier {".

*> ============================================================
*> Section 200: Chain verification logic
*> ============================================================
200-emit-verification-logic.
    display " "
    display ws-i1 "/**"
    display ws-i1 " * Result of a full chain integrity "
        "verification."
    display ws-i1 " * Field widths specified in COBOL "
        "PICTURE clauses."
    display ws-i1 " */"
    display ws-i1 "data class VerificationResult("
    display ws-i2 "val calBotId: Int,"
    display ws-i2 "val chainLength: Int,"
    display ws-i2 "val genesisValid: Boolean,"
    display ws-i2 "val allLinksValid: Boolean,"
    display ws-i2 "val allHashesWellFormed: Boolean,"
    display ws-i2 "val temporalOrderValid: Boolean,"
    display ws-i2 "val brokenLinkIndices: List<Int>,"
    display ws-i2 "val auditReport: String,"
    display ws-i2 "val integrityProofHash: String,"
    display ws-i2 "val verdict: String"
    display ws-i1 ") {"
    display ws-i2 "val isFullyValid: Boolean get() ="
    display ws-i3 "genesisValid && allLinksValid && "
        "allHashesWellFormed && temporalOrderValid"
    display ws-i1 "}"
    display " "

    display ws-i1 "/**"
    display ws-i1 " * Verify the integrity of a CalBot's "
        "blockchain."
    display ws-i1 " *"
    display ws-i1 " * Implements the COBOL-specified "
        "verification rules:"
    display ws-i1 " *   PERFORM 210-CHECK-GENESIS-ANCHOR"
    display ws-i1 " *   PERFORM 220-CHECK-CHAIN-LINKAGE"
    display ws-i1 " *   PERFORM 230-CHECK-HASH-FORMAT"
    display ws-i1 " *   PERFORM 240-CHECK-TEMPORAL-ORDER"
    display ws-i1 " */"
    display ws-i1 "fun verifyChain("
    display ws-i2 "calBotId: Int,"
    display ws-i2 "blocks: List<BlockEntity>"
    display ws-i1 "): VerificationResult {"
    display ws-i2 "if (blocks.isEmpty()) {"
    display ws-i3 "return VerificationResult("
    display ws-i4 "calBotId = calBotId,"
    display ws-i4 "chainLength = 0,"
    display ws-i4 "genesisValid = true,"
    display ws-i4 "allLinksValid = true,"
    display ws-i4 "allHashesWellFormed = true,"
    display ws-i4 "temporalOrderValid = true,"
    display ws-i4 "brokenLinkIndices = emptyList(),"
    display ws-i4 "auditReport = "
        '"' & "CHAIN EMPTY -- NO BLOCKS TO VERIFY" & '",'
    display ws-i4 "integrityProofHash = ZERO_PROOF,"
    display ws-i4 'verdict = "EMPTY"'
    display ws-i3 ")"
    display ws-i2 "}"
    display " "

    display ws-i2
        "// Sort by timestamp ascending (oldest first)"
    display ws-i2
        "val sorted = blocks.sortedBy { it.timestamp }"
    display " "
    display ws-i2 "// 210-CHECK-GENESIS-ANCHOR"
    display ws-i2
        "val genesisHash = GenesisBlocks.hashes[calBotId]"
    display ws-i3 "?: GenesisBlocks.ZERO_HASH"
    display ws-i2
        "val genesisValid = "
        "sorted.first().prevHash == genesisHash"
    display " "

    display ws-i2 "// 220-CHECK-CHAIN-LINKAGE"
    display ws-i2
        "val brokenLinks = mutableListOf<Int>()"
    display ws-i2
        "for (i in 1 until sorted.size) {"
    display ws-i3
        "if (sorted[i].prevHash != "
        "sorted[i - 1].blockHash) {"
    display ws-i4 "brokenLinks.add(i)"
    display ws-i3 "}"
    display ws-i2 "}"
    display " "

    display ws-i2 "// 230-CHECK-HASH-FORMAT"
    display ws-i2 'val hexPattern = Regex("'
        & '^[0-9a-f]{64}$")'
    display ws-i2 "val allHashesOk = sorted.all {"
    display ws-i3
        "hexPattern.matches(it.blockHash) && "
        "hexPattern.matches(it.prevHash)"
    display ws-i2 "}"
    display " "

    display ws-i2 "// 240-CHECK-TEMPORAL-ORDER"
    display ws-i2
        "val temporalOk = sorted.zipWithNext().all {"
    display ws-i3
        "(a, b) -> b.timestamp >= a.timestamp"
    display ws-i2 "}"
    display " "

    display ws-i2
        "// Generate audit report and integrity proof"
    display ws-i2
        "val report = formatAuditReport("
        "calBotId, sorted, genesisValid,"
    display ws-i3
        "brokenLinks, allHashesOk, temporalOk)"
    display ws-i2
        "val proof = computeIntegrityProof("
        "calBotId, sorted)"
    display " "
    display ws-i2 "val verdict = when {"
    display ws-i3
        "genesisValid && brokenLinks.isEmpty()"
        " && allHashesOk && temporalOk ->"
    display ws-i4 '"' & 'VERIFIED' & '"'
    display ws-i3 "brokenLinks.isNotEmpty() ->"
    display ws-i4 '"' & 'BROKEN' & '"'
    display ws-i3 "!genesisValid ->"
    display ws-i4 '"' & 'NO ANCHOR' & '"'
    display ws-i3 "else ->"
    display ws-i4 '"' & 'SUSPECT' & '"'
    display ws-i2 "}"
    display " "

    display ws-i2 "return VerificationResult("
    display ws-i3 "calBotId = calBotId,"
    display ws-i3 "chainLength = sorted.size,"
    display ws-i3 "genesisValid = genesisValid,"
    display ws-i3 "allLinksValid = brokenLinks.isEmpty(),"
    display ws-i3 "allHashesWellFormed = allHashesOk,"
    display ws-i3 "temporalOrderValid = temporalOk,"
    display ws-i3 "brokenLinkIndices = brokenLinks,"
    display ws-i3 "auditReport = report,"
    display ws-i3 "integrityProofHash = proof,"
    display ws-i3 "verdict = verdict"
    display ws-i2 ")"
    display ws-i1 "}".

*> ============================================================
*> Section 300: COBOL-style audit report formatter
*> ============================================================
300-emit-audit-formatter.
    display " "
    display ws-i1 "/**"
    display ws-i1 " * Format a COBOL-style audit report."
    display ws-i1 " */"
    display ws-i1 "private fun formatAuditReport("
    display ws-i2 "calBotId: Int,"
    display ws-i2 "blocks: List<BlockEntity>,"
    display ws-i2 "genesisValid: Boolean,"
    display ws-i2 "brokenLinks: List<Int>,"
    display ws-i2 "allHashesOk: Boolean,"
    display ws-i2 "temporalOk: Boolean"
    display ws-i1 "): String {"
    display ws-i2 "val sb = StringBuilder()"
    display " "

*>  Report header
    display ws-i2
        'sb.appendLine("=" .repeat(72))'
    display ws-i2 'sb.appendLine('
        '"  CALBOT BLOCKCHAIN INTEGRITY AUDIT REPORT")'
    display ws-i2 'sb.appendLine('
        '"  GENERATED BY: COBOL CHAIN VERIFIER '
        '(gcobol 15.2.1)")'
    display ws-i2 "sb.appendLine("
    display ws-i3
        '"  CALBOT-ID: ${calBotId.toString()' & "}"
        & '")'
    display ws-i2 "sb.appendLine("
    display ws-i3
        '"  CHAIN-LENGTH: ${blocks.size' & "}" & '")'
    display ws-i2 "sb.appendLine("
    display ws-i3 '"  GENESIS-ANCHOR: ${if '
        "(genesisValid) " & '"' & "VALID" & '"'
        & " else " & '"' & "INVALID" & '"' & "}" & '")'
    display ws-i2
        'sb.appendLine("=" .repeat(72))'
    display " "

*>  Block detail lines
    display ws-i2
        "for ((idx, block) in blocks.withIndex()) {"
    display ws-i3
        "val seq = idx.toString().padStart(6, '0')"
    display ws-i3
        "val expr = block.expression.padEnd(20)"
    display ws-i3
        "val res = block.result.toString().padStart(10)"
    display ws-i3
        "val hash = block.blockHash.take(8)"
    display ws-i3
        "val prev = block.prevHash.take(8)"
    display ws-i3 "val link = if (idx in brokenLinks) "
        '"' & "BROKEN" & '"' & " else " & '"' & "OK" & '"'
    display ws-i3 "sb.appendLine("
    display ws-i4
        '"  BLK-$seq | $expr | $res |'
        " H:$hash | P:$prev | $link" & '")'
    display ws-i2 "}"
    display " "

*>  Report footer
    display ws-i2
        'sb.appendLine("=" .repeat(72))'
    display ws-i2 "val overallVerdict = when {"
    display ws-i3
        "genesisValid && brokenLinks.isEmpty()"
        " && allHashesOk && temporalOk ->"
    display ws-i4 '"' & "CHAIN INTEGRITY: VERIFIED" & '"'
    display ws-i3 "else ->"
    display ws-i4 '"' & "CHAIN INTEGRITY: FAILED" & '"'
    display ws-i2 "}"
    display ws-i2 'sb.appendLine("  $overallVerdict")'
    display ws-i2 "sb.appendLine("
    display ws-i3 '"  BROKEN-LINKS: ${brokenLinks.size'
        & "}" & '")'
    display ws-i2 "sb.appendLine("
    display ws-i3 '"  HASH-FORMAT: ${if (allHashesOk) '
        & '"' & "CONFORMANT" & '"' & " else "
        & '"' & "NON-CONFORMANT" & '"' & "}" & '")'
    display ws-i2 "sb.appendLine("
    display ws-i3 '"  TEMPORAL-ORDER: ${if (temporalOk) '
        & '"' & "MONOTONIC" & '"' & " else "
        & '"' & "DISORDERED" & '"' & "}" & '")'
    display ws-i2
        'sb.appendLine("=" .repeat(72))'
    display ws-i2
        'sb.appendLine("  END OF AUDIT REPORT")'
    display ws-i2
        'sb.appendLine("  -- THIS REPORT WAS '
        'SPECIFIED IN COBOL --")'
    display " "
    display ws-i2 "return sb.toString()"
    display ws-i1 "}".

*> ============================================================
*> Section 400: Integrity proof hash computation
*> ============================================================
400-emit-integrity-proof.
    display " "
    display ws-i1 "/**"
    display ws-i1 " * Compute a SHA-256 integrity proof over"
    display ws-i1 " * the entire chain."
    display ws-i1 " */"
    display ws-i1 "private fun computeIntegrityProof("
    display ws-i2 "calBotId: Int,"
    display ws-i2 "blocks: List<BlockEntity>"
    display ws-i1 "): String {"
    display ws-i2 "val digest = MessageDigest"
        '.getInstance("SHA-256")'
    display ws-i2 "digest.update(calBotId.toString()"
        ".toByteArray())"
    display ws-i2 "for (block in blocks) {"
    display ws-i3
        "digest.update(block.blockHash.toByteArray())"
    display ws-i3
        "digest.update(block.prevHash.toByteArray())"
    display ws-i3
        "digest.update(block.expression.toByteArray())"
    display ws-i3
        "digest.update(block.result.toString()"
        ".toByteArray())"
    display ws-i3
        "digest.update(block.nonce.toString()"
        ".toByteArray())"
    display ws-i2 "}"
    display ws-i2 'return digest.digest().joinToString('
        & '""' & ") { " & '"%02x"' & ".format(it) }"
    display ws-i1 "}".

*> ============================================================
*> Section 500: Constants and closing brace
*> ============================================================
500-emit-footer.
    display " "
    display ws-i1 "private const val ZERO_PROOF ="
    display ws-i2 '"'
        & "0000000000000000"
        & "0000000000000000"
        & "0000000000000000"
        & "0000000000000000"
        & '"'
    display "}".
